var searchData=
[
  ['u1_0',['U1',['../classcytnx_1_1Symmetry.html#a9218fd66fc9cca64cd3d792e0019592a',1,'cytnx::Symmetry']]],
  ['uniform_1',['uniform',['../classcytnx_1_1UniTensor.html#aff470226c92a18514219cae0fbc01d5a',1,'cytnx::UniTensor::uniform(const cytnx_uint64 &amp;Nelem, const double &amp;low, const double &amp;high, const std::vector&lt; std::string &gt; &amp;in_labels={}, const unsigned int &amp;seed=std::random_device()(), const unsigned int &amp;dtype=Type.Double, const int &amp;device=Device.cpu, const std::string &amp;name=&quot;&quot;)'],['../classcytnx_1_1UniTensor.html#a5620c60459b85a44e365be8830f921bb',1,'cytnx::UniTensor::uniform(const std::vector&lt; cytnx_uint64 &gt; &amp;shape, const double &amp;low, const double &amp;high, const std::vector&lt; std::string &gt; &amp;in_labels={}, const unsigned int &amp;seed=std::random_device()(), const unsigned int &amp;dtype=Type.Double, const int &amp;device=Device.cpu, const std::string &amp;name=&quot;&quot;)'],['../namespacecytnx_1_1random.html#a10d47b459512c05fd3dad6d11ee941c5',1,'cytnx::random::uniform(const cytnx_uint64 &amp;Nelem, const double &amp;low, const double &amp;high, const int &amp;device=Device.cpu, const unsigned int &amp;seed=std::random_device()(), const unsigned int &amp;dtype=Type.Double)'],['../namespacecytnx_1_1random.html#a0230a28d5ece33c6d6278b7620fa8361',1,'cytnx::random::uniform(const std::vector&lt; cytnx_uint64 &gt; &amp;Nelem, const double &amp;low, const double &amp;high, const int &amp;device=Device.cpu, const unsigned int &amp;seed=std::random_device()(), const unsigned int &amp;dtype=Type.Double)']]],
  ['uniform_5f_2',['uniform_',['../classcytnx_1_1UniTensor.html#af2f634f75f44b4b30a3141b7f85825fa',1,'cytnx::UniTensor::uniform_()'],['../namespacecytnx_1_1random.html#acfb0b0e3b706711bae910d4bfe8e3e93',1,'cytnx::random::uniform_(cytnx::Storage &amp;Sin, const double &amp;low=0, const double &amp;high=1, const unsigned int &amp;seed=std::random_device()())'],['../namespacecytnx_1_1random.html#ac893fe2052feb68dac4d2d1787f479d6',1,'cytnx::random::uniform_(cytnx::Tensor &amp;Tin, const double &amp;low=0, const double &amp;high=1, const unsigned int &amp;seed=std::random_device()())'],['../namespacecytnx_1_1random.html#ac4e05fe642d807057ab7bceebb3a25ab',1,'cytnx::random::uniform_(cytnx::UniTensor &amp;Tin, const double &amp;low=0, const double &amp;high=1, const unsigned int &amp;seed=std::random_device()())']]],
  ['unitensor_3',['unitensor',['../classcytnx_1_1UniTensor.html#a2c9e90edc079939c00600ca4e6ab56bb',1,'cytnx::UniTensor::UniTensor(const Tensor &amp;in_tensor, const bool &amp;is_diag=false, const cytnx_int64 &amp;rowrank=-1, const std::vector&lt; std::string &gt; &amp;in_labels={}, const std::string &amp;name=&quot;&quot;)'],['../classcytnx_1_1UniTensor.html#a22bfca573fca4122e18717050f1f0a7c',1,'cytnx::UniTensor::UniTensor(const std::vector&lt; Bond &gt; &amp;bonds, const std::vector&lt; std::string &gt; &amp;in_labels={}, const cytnx_int64 &amp;rowrank=-1, const unsigned int &amp;dtype=Type.Double, const int &amp;device=Device.cpu, const bool &amp;is_diag=false, const std::string &amp;name=&quot;&quot;)']]],
  ['uten_5ftype_4',['uten_type',['../classcytnx_1_1UniTensor.html#afe930fe1d99b1149ccb65e1003c6030b',1,'cytnx::UniTensor']]],
  ['uten_5ftype_5fstr_5',['uten_type_str',['../classcytnx_1_1UniTensor.html#a1c7cfbb826a15cd3272985e6db0d9c78',1,'cytnx::UniTensor']]]
];
